/**
 * aidlc-docs — the persisted lifecycle artifact for an integration.
 *
 * plan_integration builds a rich plan (design brief, per-sub-flow prop contracts,
 * EMF index map, gap list) that previously existed only in the tool response, so
 * the design rationale evaporated when the session ended. This module persists it
 * next to the project:
 *
 *   <project>/aidlc-docs/plan.md      human-readable — read in review and handoff
 *   <project>/aidlc-docs/state.json   machine-readable — lifecycle state for tools
 *
 * See docs/ai-dlc-alignment-proposal.md (increment 1).
 *
 * NOTE: these files are meant to be committed to the user's project repo. Never
 * write credentials or tenant values here — attribute NAMES only, never values.
 */

import { mkdir, readFile, writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';

export const AIDLC_DIR = 'aidlc-docs';

/**
 * Writes plan.md + state.json into <projectPath>/aidlc-docs/.
 * Preserves `created` and the `decisions` log if state.json already exists, so
 * re-scaffolding an integration does not discard its history.
 * Returns the project-relative paths written.
 */
export async function writeAidlcDocs(projectPath, plan, { today = isoDate() } = {}) {
  const dir = join(projectPath, AIDLC_DIR);
  await mkdir(dir, { recursive: true });

  const prior = await readStateIfPresent(dir);
  const state = buildState(plan, { today, prior });

  await writeFile(join(dir, 'plan.md'), renderPlanMarkdown(plan, state), 'utf-8');
  await writeFile(join(dir, 'state.json'), JSON.stringify(state, null, 2) + '\n', 'utf-8');

  return [`${AIDLC_DIR}/plan.md`, `${AIDLC_DIR}/state.json`];
}

async function readStateIfPresent(dir) {
  const p = join(dir, 'state.json');
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(await readFile(p, 'utf-8'));
  } catch {
    return null;  // corrupt or hand-edited — regenerate rather than fail the scaffold
  }
}

// ─── state.json ───────────────────────────────────────────────────────────────

export function buildState(plan, { today = isoDate(), prior = null } = {}) {
  return {
    integration: plan.integration,
    phase: 'construction',            // Inception completed the moment a plan exists
    created: prior?.created ?? today,
    updated: today,
    design_brief: plan.design_brief,
    units_of_work: (plan.props_contract ?? []).map(c => ({
      id: c.sub_flow,
      description: c.description,
      // plan_integration scaffolds TODO stubs; nothing is built yet.
      status: 'todo_stub',
      validated_clean: false,
      error_handler: c.error_handler,
    })),
    open_gaps: plan.gaps_to_fill ?? [],
    decisions: prior?.decisions ?? [],
  };
}

// ─── plan.md ──────────────────────────────────────────────────────────────────

export function renderPlanMarkdown(plan, state) {
  const b = plan.design_brief ?? {};
  const out = [];

  out.push(`# ${plan.integration} — integration plan`, '');
  out.push('_Generated by `plan_integration`. Regenerated whenever the integration is re-scaffolded;',
    'the `decisions` log in `state.json` is preserved across regenerations._', '');

  out.push('## Design brief', '');
  out.push('| Decision | Value |', '|---|---|');
  for (const [k, v] of Object.entries(b)) {
    out.push(`| ${k.replace(/_/g, ' ')} | ${fmt(v)} |`);
  }
  out.push('');

  out.push('## Units of work (sub-flows)', '');
  out.push(`Execution chain:`, '', '```', plan.execution_chain ?? '(none)', '```', '');
  out.push('| Sub-flow | Purpose | Reads props | Writes props | Error handler |');
  out.push('|---|---|---|---|---|');
  for (const c of plan.props_contract ?? []) {
    out.push(`| \`${c.sub_flow}\` | ${c.description} | ${list(c.reads_props)} | ${list(c.writes_props)} | \`${c.error_handler}\` |`);
  }
  out.push('');

  if (plan.build_order?.length) {
    out.push('## Build order', '');
    plan.build_order.forEach((step, i) => out.push(`${i + 1}. ${step}`));
    out.push('');
  }

  if (plan.gaps_to_fill?.length) {
    out.push('## Open gaps', '',
      'Work the scaffold deliberately did not do — resolve before the integration runs.', '');
    for (const g of plan.gaps_to_fill) out.push(`- [ ] ${g}`);
    out.push('');
  }

  out.push('## Human handoff (Operations)', '');
  out.push('This MCP is local-only: it never touches a tenant. These steps are yours:', '');
  out.push('- [ ] Create/verify the referenced reports and objects in the Workday tenant');
  out.push('- [ ] Replace any `TODO_*` placeholder WIDs with real tenant values');
  out.push('- [ ] Grant the ISU the domain permissions the integration needs');
  out.push('- [ ] Configure integration attributes/credentials in the Workday UI (values never live in this repo)');
  out.push('- [ ] Deploy, launch, and check the server log (`parse_server_log`)', '');

  if (plan.auto_generated_in_workday_in?.length) {
    out.push('## Declarations generated in `cc:workday-in`', '');
    for (const a of plan.auto_generated_in_workday_in) out.push(`- ${a}`);
    out.push('');
  }

  if (plan.emf_xpath_summary && Object.keys(plan.emf_xpath_summary).length) {
    out.push('## EMF `@mixed` reference map', '',
      '_Positional diagram references at scaffold time. These shift when top-level elements are',
      'added or removed — see `get_patterns` topic="Insertion shift rule"._', '');
    out.push('| Element | Path |', '|---|---|');
    for (const [k, v] of Object.entries(plan.emf_xpath_summary)) out.push(`| ${k} | \`${v}\` |`);
    out.push('');
  }

  if (plan.warnings?.length) {
    out.push('## Warnings', '');
    for (const w of plan.warnings) out.push(`- ⚠️ ${w}`);
    out.push('');
  }

  out.push('---', '', `_Lifecycle state: \`${AIDLC_DIR}/state.json\` (phase: ${state.phase})._`);
  return out.join('\n');
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function isoDate() {
  return new Date().toISOString().slice(0, 10);
}

function fmt(v) {
  if (Array.isArray(v)) return v.length ? v.join(', ') : '_none_';
  if (v === undefined || v === null || v === '') return '_none_';
  return String(v);
}

function list(v) {
  return Array.isArray(v) && v.length ? v.map(x => `\`${x}\``).join(', ') : '_tbd_';
}
